from .user import *
from .auth import *
from .courses import *
from .program import *
from .staff import *
from .student import *
from .prerequistes import *
from .programCourses import *
from .studentCourseHistory import *
from .coursePlanCourses import *
from .coursesOfferedPerSem import *
from .coursePlan import *